// 작성자: 김진우 — 실제 건강정보 없이 홈 편집과 상담 연결 상태를 확인한다.
import { test, expect } from '@playwright/test';
test.use({ viewport: { width: 390, height: 844 }, trace: 'off', video: 'off' });
test('홈은 예시 데이터로 표시하고 편집 미리보기와 저장을 구분한다', async ({ page }) => {
  await page.goto('/?frame=1#Home');
  await expect(page.getByText('예시 화면 · 실제 건강 데이터가 아닙니다')).toBeVisible();
  await page.screenshot({ path: 'artifacts/home-chat/home.png' });
  await page.getByText('홈 편집', { exact: true }).click();
  await expect(page.getByText('항목을 고르고 순서와 내용을 편집해요')).toBeVisible();
  await page.screenshot({ path: 'artifacts/home-chat/editor.png' });
  await page.getByLabel('핵심 데이터 설정', { exact: true }).click();
  await page.getByText('수면 ✓', { exact: true }).click();
  await page.getByText('운동시간', { exact: true }).click();
  await page.getByRole('button', { name: '저장하고 홈 편집으로' }).click();
  await page.getByLabel('최근 건강검진 추가', { exact: true }).click();
  await page.getByRole('button', { name: '미리보기', exact: true }).click();
  await expect(page.getByText('홈 미리보기', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '이대로 저장' }).click();
  await expect(page.getByText('42분', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: '챗봇', exact: true }).click();
  await page.getByRole('tab', { name: '홈', exact: true }).click();
  await expect(page.getByText('42분', { exact: true })).toBeVisible();
});
test('파트너 선택·대화·파트너 전환·상담 기록 재조회', async ({ page }) => {
  await page.goto('/?frame=1#Home');
  await page.getByRole('tab', { name: '챗봇', exact: true }).click();
  await expect(page.getByText('오늘 누구와', { exact: false })).toBeVisible();
  await page.screenshot({ path: 'artifacts/home-chat/partners.png' });
  await page.getByLabel('히피멍 선택', { exact: true }).click();
  await page.getByLabel('건강 질문', { exact: true }).fill('합성 질문');
  await page.getByRole('button', { name: '질문 보내기' }).click();
  await expect(page.getByText('화면 검증용 합성 답변입니다.')).toBeVisible();
  await page.getByText('바꾸기  ›', { exact: true }).click();
  await page.getByLabel('히피냥 선택', { exact: true }).click();
  await expect(page.getByText('화면 검증용 합성 답변입니다.')).toBeVisible();
  await page.screenshot({ path: 'artifacts/home-chat/conversation.png' });
  await page.getByLabel('상담 기록 열기').click();
  await expect(page.getByText('합성 상담', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/home-chat/history.png' });
  await page.getByText('합성 상담', { exact: true }).click();
  await expect(page.getByText('화면 검증용 합성 답변입니다.')).toBeVisible();
});

test('홈 드래그 정렬과 편집 취소, 복약 표시 설정', async ({ page }) => {
  await page.goto('/?frame=1#Home');
  await page.getByText('홈 편집', { exact: true }).click();
  const handle = page.getByRole('slider', { name: 'AI 건강 브리핑 순서 변경' });
  const box = await handle.boundingBox();
  if (!box) throw new Error('드래그 손잡이를 찾지 못했습니다.');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2 + 70, { steps: 10 });
  await page.mouse.up();
  const moved = await handle.boundingBox();
  expect(moved!.y).toBeGreaterThan(box.y + 50);
  await page.getByLabel('오늘의 복약 추가', { exact: true }).click();
  await page.getByLabel('오늘의 복약 설정', { exact: true }).click();
  await page.getByText('오늘 전체 일정', { exact: true }).click();
  await page.getByRole('switch', { name: '약 이름과 복용량', exact: true }).click();
  await page.getByRole('button', { name: '저장하고 홈 편집으로' }).click();
  await page.getByLabel('뒤로', { exact: true }).click();
  await expect(page.getByText('오늘의 복약', { exact: true })).toHaveCount(0);
  await page.getByText('홈 편집', { exact: true }).click();
  await expect(page.getByLabel('오늘의 복약 추가', { exact: true })).toBeVisible();
});
