package com.heapy.terms.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.heapy.HeapyBackendApplication;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

@ActiveProfiles("test")
@SpringBootTest(classes = HeapyBackendApplication.class)
class UserTermsConsentRepositoryTest {

    private static final UUID USER_ID = UUID.fromString("9cf0cf52-b838-4f29-9756-858d45038ca5");

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private UserTermsConsentRepository repository;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("drop table if exists public.user_terms_consents");
        jdbcTemplate.execute("drop table if exists public.terms");
        jdbcTemplate.execute("""
                create table public.terms (
                    terms_id bigint generated by default as identity primary key,
                    terms_code varchar not null,
                    version varchar not null,
                    is_required boolean not null,
                    effective_at timestamp with time zone not null,
                    retired_at timestamp with time zone
                )
                """);
        jdbcTemplate.execute("""
                create table public.user_terms_consents (
                    consent_id bigint generated by default as identity primary key,
                    user_id uuid not null,
                    terms_id bigint not null,
                    action varchar not null,
                    occurred_at timestamp with time zone not null
                )
                """);
    }

    @Test
    void 같은_약관_코드의_현재_최신_버전에_동의해야_완료로_판정한다() {
        long oldServiceTermsId = insertTerms("service", "1.0", "-10");
        long currentServiceTermsId = insertTerms("service", "2.0", "-1");
        long privacyTermsId = insertTerms("privacy", "1.0", "-2");
        insertConsent(oldServiceTermsId, "agreed", "-3");
        insertConsent(privacyTermsId, "agreed", "-1");

        assertThat(repository.countMissingCurrentRequiredConsents(USER_ID)).isEqualTo(1L);

        insertConsent(currentServiceTermsId, "agreed", "0");
        assertThat(repository.countMissingCurrentRequiredConsents(USER_ID)).isZero();
    }

    @Test
    void 최신_동의_이벤트가_철회면_미동의로_판정한다() {
        long termsId = insertTerms("service", "1.0", "-2");
        insertConsent(termsId, "agreed", "-1");
        insertConsent(termsId, "revoked", "0");

        assertThat(repository.countMissingCurrentRequiredConsents(USER_ID)).isEqualTo(1L);
    }

    private long insertTerms(String code, String version, String dayOffset) {
        jdbcTemplate.update("""
                insert into public.terms (
                    terms_code, version, is_required, effective_at, retired_at
                ) values (?, ?, true, dateadd('day', ?, current_timestamp), null)
                """, code, version, Integer.parseInt(dayOffset));
        return jdbcTemplate.queryForObject("select max(terms_id) from public.terms", Long.class);
    }

    private void insertConsent(long termsId, String action, String minuteOffset) {
        jdbcTemplate.update("""
                insert into public.user_terms_consents (user_id, terms_id, action, occurred_at)
                values (?, ?, ?, dateadd('minute', ?, current_timestamp))
                """, USER_ID, termsId, action, Integer.parseInt(minuteOffset));
    }
}
